### PR TITLE
clean up recipe, bump build number for missing anaconda.org

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Notes:
- pretty much just because #7 was never uploaded:
  - https://anaconda.org/conda-forge/devpi-common/files?version=4.0.4 

Changes:
- [x] remove jinja var tricks for `name`
- [x] update pip invocation

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge/devpi-common ready for review

**Comment by thewchan** [comment]
@bollwyvl I've ran the pipeline so it should all be good, it might take a few for the all the CDN to grab 4.0.4 but the files are there

**Comment by thewchan** [comment]
@bollwyvl let me know if you still want me to merge this given that you also added a couple flags to the build line

**Comment by bollwyvl** [comment]
either way. they _are_ the defauls (by env var), but good to have anyway for local testing where it's _not_ automagic.

**Comment by thewchan** [comment]
cool sure I can merge. Thanks!

**Pull request merged**
